/**
 *  suggestions object for performance rating
 *  @type {Object}
 *  @property {string[]} 4 - Suggestions for performance rating 4
 *  @property {string[]} 3 - Suggestions for performance rating 3
 *  @property {string[]} 2 - Suggestions for performance rating 2
 *  @property {string[]} 1 - Suggestions for performance rating 1
 */
export const suggestions = {
    4: [
      "Consider investing surplus in stocks or mutual funds.",
      "Look into long-term retirement plans for stable growth.",
      "Explore diversified investment options for higher returns.",
      "Invest in index funds to minimize risk while growing wealth.",
      "Consider automating investments with recurring deposits.",
      "Set aside a portion of income for high-yield savings accounts.",
      "Review investment portfolio regularly and rebalance if needed.",
      "Try peer-to-peer lending platforms with caution.",
      "Consider learning about real estate investments.",
      "Invest in ETFs to spread out risk across industries.",
      "Explore sustainable or ESG investments.",
      "Plan for tax-efficient investing.",
      "Take small calculated risks to grow capital.",
      "Use financial apps to track investments and performance.",
      "Keep an emergency fund separate from investments.",
      "Learn about cryptocurrency investing cautiously.",
      "Consider international diversification for your portfolio.",
      "Automate monthly contributions to retirement accounts.",
      "Attend investment webinars or workshops to improve knowledge.",
      "Track investment performance quarterly.",
      "Consider low-cost robo-advisors for diversified investments.",
      "Explore dividend-paying stocks for passive income.",
      "Set a clear investment goal for the next 3–5 years.",
      "Avoid making emotional investment decisions.",
      "Use tax-advantaged accounts for long-term growth.",
      "Research new market opportunities before investing.",
      "Review financial news to stay informed about trends.",
      "Start a side business to reinvest profits.",
      "Create multiple income streams for stability.",
      "Consider socially responsible investments for ethical growth."
    ],
    3: [
      "Try saving more or start small recurring investments.",
      "Track monthly expenses to increase your savings rate.",
      "Set achievable short-term financial goals.",
      "Consider a small emergency fund for security.",
      "Review subscriptions and cut unnecessary spending.",
      "Try the 50/30/20 budgeting rule.",
      "Automate small monthly savings.",
      "Consider saving spare change using apps.",
      "Avoid lifestyle inflation when income increases.",
      "Look for cashback or reward programs on regular spending.",
      "Start a side hustle for extra income.",
      "Compare prices before making major purchases.",
      "Plan weekly grocery budget to reduce waste.",
      "Use digital tools to track recurring bills.",
      "Set a savings target for the next 6 months.",
      "Avoid unnecessary luxury purchases for now.",
      "Track your spending categories monthly.",
      "Set reminders for bill payments to avoid late fees.",
      "Review insurance plans to ensure adequate coverage.",
      "Start small investments in mutual funds or ETFs.",
      "Build a mini emergency fund for unexpected expenses.",
      "Focus on reducing monthly recurring costs.",
      "Negotiate service contracts or bills for better rates.",
      "Use budgeting apps to create realistic plans.",
      "Start a savings challenge with small weekly goals.",
      "Avoid impulse shopping online.",
      "Review your financial goals quarterly.",
      "Try cash-back apps or loyalty programs.",
      "Learn basic investing concepts for future growth.",
      "Track your net worth progress monthly."
    ],
    2: [
      "Cut unnecessary spending and track monthly budget closely.",
      "Create a detailed budget to monitor income vs expenses.",
      "Avoid impulse purchases to stabilize finances.",
      "Use free budgeting apps to keep track of spending.",
      "Negotiate bills and look for cheaper alternatives.",
      "Cook meals at home instead of dining out.",
      "Sell unused items to raise quick cash.",
      "Pause subscription services that aren’t essential.",
      "Limit credit card usage to essentials only.",
      "Plan shopping lists to avoid overspending.",
      "Set a small daily spending limit.",
      "Track fuel or transport expenses and optimize routes.",
      "Look for free or low-cost entertainment options.",
      "Switch to generic brands for some essentials.",
      "Create a financial checklist for monthly priorities.",
      "Avoid eating out frequently to save money.",
      "Track utility bills and reduce unnecessary usage.",
      "Use public transport or carpool to cut costs.",
      "Consider a temporary spending freeze on non-essential items.",
      "Make a list before shopping to avoid impulse buys.",
      "Prioritize high-interest payments to reduce debt faster.",
      "Check bank statements for hidden charges.",
      "Look for seasonal discounts when buying essentials.",
      "Set short-term financial targets to stay motivated.",
      "Avoid using payday loans or high-interest credit.",
      "Track progress on a weekly basis.",
      "Review past spending habits and adjust accordingly.",
      "Avoid unnecessary fees by paying bills on time.",
      "Use cash for discretionary expenses to limit spending.",
      "Start a small savings envelope system for better control."
    ],
    1: [
      "Consider debt management or temporary expense freeze.",
      "Prioritize paying off high-interest debts first.",
      "Seek financial advice for urgent money management.",
      "Temporarily reduce discretionary spending.",
      "Focus on essentials and postpone major purchases.",
      "Avoid taking new loans or credit until debt is managed.",
      "Make a debt repayment plan with realistic timelines.",
      "Negotiate payment terms with creditors if needed.",
      "Use free financial counseling resources.",
      "Track every expense to understand cash flow.",
      "Use cash instead of cards to avoid overspending.",
      "Share financial responsibility with family if possible.",
      "Consider side income to pay off urgent debt.",
      "Temporarily pause savings if debt interest is high.",
      "Focus on financial survival before investment.",
      "Avoid large purchases or travel until finances stabilize.",
      "Pay off small debts first to build momentum.",
      "Cut back on unnecessary utilities or subscriptions.",
      "Prioritize urgent bills like rent, utilities, and groceries.",
      "Use community or government support programs if needed.",
      "Track daily spending meticulously to avoid overspending.",
      "Negotiate debt settlements when possible.",
      "Seek low-interest repayment plans.",
      "Avoid payday loans or high-interest financing.",
      "Set realistic weekly budgets and stick to them.",
      "Focus on essential needs over wants.",
      "Consolidate debts if it lowers interest rates.",
      "Avoid borrowing from multiple sources at once.",
      "Educate yourself about debt reduction strategies.",
      "Celebrate small wins to stay motivated."
    ],
    0: [
      "You are heavily in debt — prioritize immediate debt reduction.",
      "List all debts and focus on high-interest loans first.",
      "Temporarily stop discretionary spending entirely.",
      "Seek professional financial counseling immediately.",
      "Negotiate payment plans with creditors where possible.",
      "Consider debt consolidation to reduce interest rates.",
      "Temporarily pause any investments until debt is managed.",
      "Track every expense daily to avoid further debt.",
      "Use cash-only budgeting to control spending strictly.",
      "Avoid taking new credit or loans under any circumstances.",
      "Share financial responsibility with family or support system.",
      "Look for additional income sources to accelerate debt repayment.",
      "Set small achievable weekly debt repayment targets.",
      "Focus on essentials: food, rent, utilities first.",
      "Avoid large purchases, travel, or luxury items entirely.",
      "Automate minimum payments to avoid late fees.",
      "Consider selling non-essential assets to pay off debts.",
      "Educate yourself on debt reduction strategies immediately.",
      "Celebrate small wins to stay motivated while reducing debt.",
      "Use community or government support programs if necessary."
    ]
  };
  