
export const suggestions_old_BKP = {
    4: [
      "Consider investing surplus in stocks or mutual funds.",
      "Look into long-term retirement plans for stable growth.",
      "Explore diversified investment options for higher returns.",
      "Invest in index funds to minimize risk while growing wealth.",
      "Consider automating investments with recurring deposits.",
      "Set aside a portion of income for high-yield savings accounts.",
      "Review investment portfolio regularly and rebalance if needed.",
      "Try peer-to-peer lending platforms with caution.",
      "Consider learning about real estate investments.",
      "Invest in ETFs to spread out risk across industries.",
      "Explore sustainable or ESG investments.",
      "Plan for tax-efficient investing.",
      "Take small calculated risks to grow capital.",
      "Use financial apps to track investments and performance.",
      "Keep an emergency fund separate from investments.",
      "Learn about cryptocurrency investing cautiously.",
      "Consider international diversification for your portfolio.",
      "Automate monthly contributions to retirement accounts.",
      "Attend investment webinars or workshops to improve knowledge.",
      "Track investment performance quarterly.",
      "Consider low-cost robo-advisors for diversified investments.",
      "Explore dividend-paying stocks for passive income.",
      "Set a clear investment goal for the next 3–5 years.",
      "Avoid making emotional investment decisions.",
      "Use tax-advantaged accounts for long-term growth.",
      "Research new market opportunities before investing.",
      "Review financial news to stay informed about trends.",
      "Start a side business to reinvest profits.",
      "Create multiple income streams for stability.",
      "Consider socially responsible investments for ethical growth."
    ],
    3: [
      "Try saving more or start small recurring investments.",
      "Track monthly expenses to increase your savings rate.",
      "Set achievable short-term financial goals.",
      "Consider a small emergency fund for security.",
      "Review subscriptions and cut unnecessary spending.",
      "Try the 50/30/20 budgeting rule.",
      "Automate small monthly savings.",
      "Consider saving spare change using apps.",
      "Avoid lifestyle inflation when income increases.",
      "Look for cashback or reward programs on regular spending.",
      "Start a side hustle for extra income.",
      "Compare prices before making major purchases.",
      "Plan weekly grocery budget to reduce waste.",
      "Use digital tools to track recurring bills.",
      "Set a savings target for the next 6 months.",
      "Avoid unnecessary luxury purchases for now.",
      "Track your spending categories monthly.",
      "Set reminders for bill payments to avoid late fees.",
      "Review insurance plans to ensure adequate coverage.",
      "Start small investments in mutual funds or ETFs.",
      "Build a mini emergency fund for unexpected expenses.",
      "Focus on reducing monthly recurring costs.",
      "Negotiate service contracts or bills for better rates.",
      "Use budgeting apps to create realistic plans.",
      "Start a savings challenge with small weekly goals.",
      "Avoid impulse shopping online.",
      "Review your financial goals quarterly.",
      "Try cash-back apps or loyalty programs.",
      "Learn basic investing concepts for future growth.",
      "Track your net worth progress monthly."
    ],
    2: [
      "Cut unnecessary spending and track monthly budget closely.",
      "Create a detailed budget to monitor income vs expenses.",
      "Avoid impulse purchases to stabilize finances.",
      "Use free budgeting apps to keep track of spending.",
      "Negotiate bills and look for cheaper alternatives.",
      "Cook meals at home instead of dining out.",
      "Sell unused items to raise quick cash.",
      "Pause subscription services that aren’t essential.",
      "Limit credit card usage to essentials only.",
      "Plan shopping lists to avoid overspending.",
      "Set a small daily spending limit.",
      "Track fuel or transport expenses and optimize routes.",
      "Look for free or low-cost entertainment options.",
      "Switch to generic brands for some essentials.",
      "Create a financial checklist for monthly priorities.",
      "Avoid eating out frequently to save money.",
      "Track utility bills and reduce unnecessary usage.",
      "Use public transport or carpool to cut costs.",
      "Consider a temporary spending freeze on non-essential items.",
      "Make a list before shopping to avoid impulse buys.",
      "Prioritize high-interest payments to reduce debt faster.",
      "Check bank statements for hidden charges.",
      "Look for seasonal discounts when buying essentials.",
      "Set short-term financial targets to stay motivated.",
      "Avoid using payday loans or high-interest credit.",
      "Track progress on a weekly basis.",
      "Review past spending habits and adjust accordingly.",
      "Avoid unnecessary fees by paying bills on time.",
      "Use cash for discretionary expenses to limit spending.",
      "Start a small savings envelope system for better control."
    ],
    1: [
      "Consider debt management or temporary expense freeze.",
      "Prioritize paying off high-interest debts first.",
      "Seek financial advice for urgent money management.",
      "Temporarily reduce discretionary spending.",
      "Focus on essentials and postpone major purchases.",
      "Avoid taking new loans or credit until debt is managed.",
      "Make a debt repayment plan with realistic timelines.",
      "Negotiate payment terms with creditors if needed.",
      "Use free financial counseling resources.",
      "Track every expense to understand cash flow.",
      "Use cash instead of cards to avoid overspending.",
      "Share financial responsibility with family if possible.",
      "Consider side income to pay off urgent debt.",
      "Temporarily pause savings if debt interest is high.",
      "Focus on financial survival before investment.",
      "Avoid large purchases or travel until finances stabilize.",
      "Pay off small debts first to build momentum.",
      "Cut back on unnecessary utilities or subscriptions.",
      "Prioritize urgent bills like rent, utilities, and groceries.",
      "Use community or government support programs if needed.",
      "Track daily spending meticulously to avoid overspending.",
      "Negotiate debt settlements when possible.",
      "Seek low-interest repayment plans.",
      "Avoid payday loans or high-interest financing.",
      "Set realistic weekly budgets and stick to them.",
      "Focus on essential needs over wants.",
      "Consolidate debts if it lowers interest rates.",
      "Avoid borrowing from multiple sources at once.",
      "Educate yourself about debt reduction strategies.",
      "Celebrate small wins to stay motivated."
    ],
    0: [
      "You are heavily in debt — prioritize immediate debt reduction.",
      "List all debts and focus on high-interest loans first.",
      "Temporarily stop discretionary spending entirely.",
      "Seek professional financial counseling immediately.",
      "Negotiate payment plans with creditors where possible.",
      "Consider debt consolidation to reduce interest rates.",
      "Temporarily pause any investments until debt is managed.",
      "Track every expense daily to avoid further debt.",
      "Use cash-only budgeting to control spending strictly.",
      "Avoid taking new credit or loans under any circumstances.",
      "Share financial responsibility with family or support system.",
      "Look for additional income sources to accelerate debt repayment.",
      "Set small achievable weekly debt repayment targets.",
      "Focus on essentials: food, rent, utilities first.",
      "Avoid large purchases, travel, or luxury items entirely.",
      "Automate minimum payments to avoid late fees.",
      "Consider selling non-essential assets to pay off debts.",
      "Educate yourself on debt reduction strategies immediately.",
      "Celebrate small wins to stay motivated while reducing debt.",
      "Use community or government support programs if necessary.",
      "Set a clear debt repayment goal for the next 6 months.",
      "Prioritize debt repayment over other financial goals.",
      
    ]
  };
  /**
 *  suggestions object for performance rating
 *  @type {Object}
 *  @property {string[]} 4 - Suggestions for performance rating 4
 *  @property {string[]} 3 - Suggestions for performance rating 3
 *  @property {string[]} 2 - Suggestions for performance rating 2
 *  @property {string[]} 1 - Suggestions for performance rating 1
 */
  export const suggestions = {
    4: [ // Excellent performance
      "Invest in ethical funds or socially responsible businesses that align with your values and risk tolerance.",
      "Save and automate your wealth growth regularly to ensure consistent financial progress without relying on memory.",
      "Track spending and savings meticulously to understand cash flow and optimize allocations each month.",
      "Diversify income sources legally and ethically to reduce dependency on a single source of revenue.",
      "Invest in real estate or property safely, considering location, long-term growth, and market trends.",
      "Donate a portion of your wealth to charity to support your community and create positive social impact.",
      "Set long-term financial goals with specific timelines and milestones to measure progress effectively.",
      "Use digital tools or apps to monitor income, expenses, and investments for better financial visibility.",
      "Improve skills continuously to increase income potential and career opportunities ethically.",
      "Keep emergency funds covering 6–12 months of essential expenses to safeguard against unforeseen events.",
      "Reinvest profits from business or investments to accelerate wealth growth while minimizing idle cash.",
      "Review subscriptions and recurring expenses quarterly to eliminate unnecessary payments.",
      "Plan major purchases responsibly, comparing options and considering both cost and value over time.",
      "Build multiple passive income streams that comply with ethical and halal standards.",
      "Use apps to set and track financial goals, ensuring alignment with long-term wealth objectives.",
      "Plan for children’s education ethically by investing in secure and long-term savings plans.",
      "Invest in health or insurance plans to protect your financial stability and personal wellbeing.",
      "Monitor investments regularly to evaluate performance and adjust strategies as needed.",
      "Balance spending, saving, and investing to maintain financial health and lifestyle sustainability.",
      "Invest in socially responsible projects that align with your personal values and ethical standards.",
      "Review financial goals quarterly and adjust strategies based on progress and market conditions.",
      "Track portfolio growth monthly to measure returns and rebalance allocations effectively.",
      "Participate in ethical crowdfunding contributions to support innovative projects responsibly.",
      "Use ethical digital wallets effectively to manage day-to-day transactions securely.",
      "Monitor recurring income sources and ensure they are stable and compliant with your financial plan.",
      "Keep multiple accounts for fund segmentation to separate savings, investments, and daily spending.",
      "Plan lifestyle upgrades responsibly, ensuring they do not negatively impact long-term financial goals.",
      "Use budgeting tools to visualize spending patterns and identify areas for improvement.",
      "Allocate funds for professional development, including courses and certifications that enhance income potential.",
      "Invest in small ethical startups after thorough research to generate returns responsibly.",
      "Leverage compound growth for savings and investments to maximize long-term financial benefits.",
      "Set aside funds for emergencies regularly to ensure liquidity during unexpected situations.",
      "Track discretionary spending monthly to prevent unnecessary outflows from your budget.",
      "Invest in educational courses ethically to improve skills and increase future earning potential.",
      "Use rewards or cashback programs responsibly to enhance value from everyday spending.",
      "Plan for seasonal or festival-related expenses without disrupting regular budget allocations.",
      "Rebalance investment portfolios for risk management and to align with current market conditions.",
      "Audit finances periodically to find inefficiencies and optimize cash flow.",
      "Automate bill payments to avoid late fees and maintain a positive financial record.",
      "Maintain liquidity to seize investment opportunities when they arise.",
      "Track financial milestones annually to celebrate progress and adjust long-term strategies.",
      "Plan leisure spending responsibly to enjoy life while staying within budget.",
      "Focus on wealth preservation alongside growth to protect assets in volatile markets.",
      "Use financial alerts for reminders about payments, investments, and account balances.",
      "Explore ethical investment platforms that provide transparency and sustainable growth opportunities.",
      "Invest in technology or tools that improve financial efficiency and tracking.",
      "Allocate surplus funds strategically to balance short-term needs with long-term growth.",
      "Track net worth periodically to monitor overall financial health and adjust strategies.",
      "Set multiple short-term and long-term goals to maintain focus and measure success effectively.",
      "Use goal-based investing strategies to direct funds toward specific financial outcomes.",
      "Plan charitable contributions regularly to align with personal values and tax planning.",
      "Monitor insurance coverage and updates to ensure comprehensive protection.",
      "Invest in income-generating assets ethically to create reliable, halal revenue streams.",
      "Review subscriptions quarterly and eliminate unnecessary or redundant services.",
      "Track recurring expenses carefully to prevent small leaks from affecting financial stability.",
      "Maintain balance in all financial aspects including savings, spending, and investing.",
      "Reinvest returns to accelerate growth and compound wealth over time.",
      "Use apps to analyze spending patterns and optimize monthly budgets effectively.",
      "Review financial strategies annually to adjust for life changes and economic conditions.",
      "Stay disciplined with discretionary spending to avoid impulsive purchases.",
      "Automate savings across multiple accounts for specific purposes like emergencies or goals.",
      "Track cash inflow vs outflow precisely to understand financial health and opportunities."
    ],
  
    3: [ // Good performance
      "Track monthly expenses to identify areas where you can save without compromising essentials.",
      "Set a monthly budget for all categories and review it regularly to maintain control over finances.",
      "Automate a portion of your savings every month to ensure consistent wealth accumulation.",
      "Cancel unused subscriptions or recurring services that do not add value to your life.",
      "Check bills and recurring charges monthly to avoid overpayment and unnecessary fees.",
      "Invest in low-risk halal options that provide steady returns while maintaining ethical standards.",
      "Build an emergency fund covering 3–6 months of essential expenses to handle unforeseen events.",
      "Track all income sources carefully to maintain clarity on cash inflows and financial stability.",
      "Plan quarterly financial reviews to assess progress on goals and adjust strategies accordingly.",
      "Avoid impulsive big purchases by creating a waiting period and evaluating the need carefully.",
      "Set short-term financial goals for each quarter to maintain momentum and motivation.",
      "Use budgeting apps consistently to track spending patterns and optimize savings effectively.",
      "Adjust spending based on progress and identify categories where you can reduce costs ethically.",
      "Plan ethical small investments monthly to gradually grow wealth without taking unnecessary risks.",
      "Keep a buffer for unexpected costs to avoid financial strain and emergencies.",
      "Track your savings rate and progress towards goals each month to maintain accountability.",
      "Use spreadsheets or apps to monitor cash flow and visualize your financial position clearly.",
      "Limit discretionary spending responsibly to prevent overspending and preserve wealth.",
      "Allocate funds for meaningful goals such as education, charity, or personal development.",
      "Reward yourself modestly for achieving financial targets to maintain motivation.",
      "Review progress on all financial goals quarterly to ensure alignment with long-term plans.",
      "Track recurring income and expenses to spot patterns and optimize cash management.",
      "Adjust budget allocations monthly based on changes in income or expenses.",
      "Monitor cash inflow vs outflow weekly to ensure positive net cash flow consistently.",
      "Invest in ethical micro-projects to diversify income streams safely.",
      "Check insura nce coverage periodically to make sure you are adequately protected.",
      "Plan minor expenses in advance to avoid last-minute impulsive spending.",
      "Track utility and subscription costs monthly and identify areas to save.",
      "Avoid unnecessary high-interest debts that can drain financial resources.",
      "Focus on essential expenses before luxuries to maintain stability and control.",
      "Use discounts and offers responsibly to save money on necessary purchases.",
      "Track investments and returns monthly to evaluate performance and make informed decisions.",
      "Maintain emergency fund liquidity to be able to cover urgent expenses when needed.",
      "Plan for seasonal spending responsibly to avoid overspending during festivals or holidays.",
      "Rebalance low-risk investments quarterly to optimize returns and minimize risk.",
      "Analyze spending trends monthly to identify patterns and improve financial behavior.",
      "Set aside funds for personal growth and education to increase future income potential.",
      "Track small daily expenses to prevent unnoticed leaks in your budget.",
      "Prioritize essential purchases before discretionary items to ensure stability.",
      "Avoid impulsive spending by creating lists and following them strictly.",
      "Plan charity contributions monthly to give consistently and ethically.",
      "Track discretionary spending carefully to maintain balance between wants and needs.",
      "Use apps to track recurring bills and due dates to prevent late payments.",
      "Monitor cash balances weekly to ensure funds are allocated efficiently.",
      "Allocate savings for short-term goals such as vacations or purchases.",
      "Adjust budget for unexpected events like medical bills or urgent repairs.",
      "Use reward programs ethically to benefit from everyday transactions responsibly.",
      "Plan vacations or leisure activities within a pre-set budget to avoid overspending.",
      "Review subscriptions quarterly and cancel redundant or unused services.",
      "Track progress on long-term goals to ensure alignment with strategic financial plans.",
      "Focus on gradual wealth growth through consistent savings and ethical investments.",
      "Use budgeting reminders effectively to stay on track with all financial obligations.",
      "Invest in skills and certifications that can increase income ethically.",
      "Maintain balance between income, spending, and saving to avoid financial stress.",
      "Monitor spending versus income weekly to detect deviations from the plan.",
      "Plan leisure spending responsibly to enjoy life without compromising savings.",
      "Review small debts and pay off strategically to minimize interest and avoid penalties.",
      "Adjust financial strategies quarterly based on changes in income, expenses, or priorities.",
      "Use tools to visualize net worth and overall financial health clearly.",
      "Avoid unnecessary high-risk commitments that could negatively impact finances.",
      "Focus on consistent ethical savings to build long-term financial security."
    ],
  
    2: [ // Average performance
      "Track weekly expenses to identify small leaks and unnecessary spending areas.",
      "Pause non-essential purchases temporarily to stabilize finances and increase savings.",
      "Pay bills on time to avoid late fees and maintain a positive financial record.",
      "Set a small emergency fund goal to cover urgent unexpected expenses.",
      "Avoid unnecessary loans that could increase financial stress or interest obligations.",
      "Focus on paying off high-interest debts ethically to reduce financial burden over time.",
      "Compare prices before buying to ensure you get value for your money.",
      "Reduce entertainment or dining out costs temporarily to free up extra funds.",
      "Track daily cash inflow and outflow to maintain awareness of spending patterns.",
      "Plan essential purchases ahead to avoid impulsive buying decisions.",
      "Freeze unnecessary subscriptions temporarily to save money for important needs.",
      "Avoid risky investments temporarily until financial stability is achieved.",
      "Build a stable monthly cash surplus to create a buffer for emergencies.",
      "Track debt repayment weekly to monitor progress and avoid penalties.",
      "Focus on essentials first to ensure critical needs are covered.",
      "Use budgeting apps or free tools consistently to stay organized and informed.",
      "Limit discretionary spending temporarily to prevent overspending.",
      "Track utility and grocery expenses carefully to reduce wastage and save money.",
      "Sell unused items ethically for extra cash to supplement income.",
      "Plan weekly meals to save on food costs and reduce waste.",
      "Track minor recurring payments to avoid unnoticed expenses.",
      "Avoid impulse buying by creating lists and sticking to them.",
      "Negotiate better terms for essential services to reduce financial burden ethically.",
      "Keep a buffer for emergencies to prevent financial stress during unexpected events.",
      "Monitor savings growth monthly to ensure progress toward goals.",
      "Check recurring subscriptions regularly to cancel unnecessary ones.",
      "Plan for seasonal expenses ahead of time to avoid last-minute financial strain.",
      "Focus on debt repayment before making discretionary purchases.",
      "Track cash flow weekly to identify areas for improvement and optimization.",
      "Limit non-essential entertainment temporarily to stabilize finances.",
      "Use lists to plan purchases and prevent impulsive spending.",
      "Avoid taking new loans unless strictly necessary and halal.",
      "Track small daily expenses to maintain clarity and control over finances.",
      "Allocate funds for important goals such as emergency funds or education.",
      "Review spending patterns weekly to detect inefficiencies or overspending.",
      "Pause luxury purchases temporarily to focus on essentials and savings.",
      "Use budgeting tools consistently to stay on track with your financial plan.",
      "Maintain minimal discretionary spending until financial stability improves.",
      "Focus on essentials to stabilize finances and build a strong foundation.",
      "Track progress on financial goals regularly to stay accountable.",
      "Plan ethical micro-investments carefully to grow wealth gradually.",
      "Monitor utility costs for efficiency and savings opportunities.",
      "Prioritize necessary healthcare spending to maintain wellbeing.",
      "Avoid high-risk commitments that may compromise financial security.",
      "Review grocery and food expenses to prevent wastage and overspending.",
      "Plan essential purchases weekly to spread out financial obligations.",
      "Track discretionary spending carefully to avoid overspending on wants.",
      "Avoid borrowing from multiple sources to prevent debt accumulation.",
      "Use financial alerts to stay on top of bills and deadlines.",
      "Prioritize urgent debts to reduce interest costs and improve credit.",
      "Maintain an emergency cash reserve for unexpected situations.",
      "Track recurring fees and payments to avoid unnoticed expenses.",
      "Avoid impulsive spending habits to strengthen financial discipline.",
      "Focus on cash inflow management to ensure expenses do not exceed income.",
      "Plan weekly financial priorities to stay organized and on track.",
      "Monitor debt interest and payments to avoid unnecessary costs.",
      "Use free tools to track finances efficiently and without extra cost.",
      "Focus on essentials over wants to maintain financial stability.",
      "Adjust budget for unexpected costs to prevent financial stress.",
      "Track monthly income and expenses accurately for better planning."
    ],
  
    1: [ // Below average performance
      "Spend only on essentials and temporarily halt all non-critical purchases.",
      "Pause all discretionary spending to focus on stabilizing finances.",
      "Pay urgent bills and rent first to prevent late fees and penalties.",
      "Track every expense carefully to avoid waste and unnoticed leaks.",
      "Avoid new loans to prevent increasing financial obligations.",
      "Cut non-essential subscriptions immediately to free up cash flow.",
      "Use cash for daily spending to maintain control over finances.",
      "Build a small emergency fund to handle urgent unexpected costs.",
      "Reduce entertainment and dining out expenses until stability improves.",
      "Delay non-critical purchases to focus on immediate financial priorities.",
      "Track debts and repayment dates to prevent defaults and penalties.",
      "Avoid impulse buying by making a list and sticking to it.",
      "Freeze investments temporarily until finances are more stable.",
      "Negotiate lower payments ethically with service providers.",
      "Focus on essential needs such as food, transport, and utilities first.",
      "Track cash flow daily to maintain visibility and control over funds.",
      "Avoid using credit cards unnecessarily to prevent accumulating debt.",
      "Prioritize urgent financial obligations before discretionary spending.",
      "Use lists to prevent impulsive or unnecessary purchases.",
      "Temporarily stop non-essential subscriptions to reduce outflows.",
      "Monitor recurring bills to ensure only necessary payments are made.",
      "Track grocery spending carefully to prevent overspending on food.",
      "Limit fuel or travel costs temporarily to save money for essentials.",
      "Avoid luxury purchases temporarily to prioritize urgent needs.",
      "Prioritize small debt repayment to gradually reduce financial pressure.",
      "Check emergency fund regularly to ensure it is sufficient for urgent needs.",
      "Track utility payments carefully to avoid missing due dates.",
      "Focus on essential healthcare expenses to maintain wellbeing.",
      "Pause online shopping temporarily to reduce impulsive spending.",
      "Track spending weekly to identify problem areas and adjust.",
      "Avoid non-essential leisure activities until finances stabilize.",
      "Negotiate payment terms responsibly to prevent late fees or penalties.",
      "Focus on debt reduction before pursuing additional savings or investments.",
      "Track savings and cash reserves to maintain visibility of funds.",
      "Limit discretionary communication expenses temporarily.",
      "Avoid borrowing from multiple sources to prevent debt accumulation.",
      "Track essential expenses daily to prevent overspending.",
      "Freeze unnecessary recurring payments to improve cash flow.",
      "Track financial priorities weekly to stay focused on urgent needs.",
      "Avoid high-risk commitments until finances improve.",
      "Focus on stabilizing cash flow before pursuing growth.",
      "Temporarily suspend subscriptions to reduce financial pressure.",
      "Use a strict daily budget tracker to monitor spending.",
      "Avoid using savings for non-essential items to maintain security.",
      "Track emergency fund growth to ensure readiness for unexpected expenses.",
      "Focus on urgent short-term financial needs first.",
      "Monitor cash inflow and outflow carefully for visibility.",
      "Track spending categories weekly to prevent unnoticed leaks.",
      "Avoid impulse or online purchases until finances improve.",
      "Maintain strict financial discipline to regain stability.",
      "Prioritize paying rent and utilities to prevent penalties.",
      "Track daily expenses carefully to maintain control.",
      "Use lists to prevent overspending or impulsive behavior.",
      "Focus only on essential items until financial health improves.",
      "Track progress on urgent debts to maintain accountability.",
      "Pause non-critical investments temporarily to conserve cash."
    ],
  
    0: [ // Critical performance
      "Repay urgent debts immediately to avoid further financial penalties or interest.",
      "Stop all non-essential spending to focus entirely on critical financial obligations.",
      "Seek emergency financial help ethically if cash flow is insufficient to cover needs.",
      "Negotiate payment deferrals responsibly with creditors to prevent defaults.",
      "Sell unnecessary assets to raise cash for urgent obligations.",
      "Pause all subscriptions and discretionary payments temporarily to conserve funds.",
      "Focus solely on daily essentials such as food, utilities, and transportation.",
      "Track cash flow multiple times per day to ensure complete visibility of funds.",
      "Seek professional financial advice urgently to stabilize your situation.",
      "Limit spending strictly to essentials to avoid running out of funds.",
      "Pause leisure or luxury spending until finances are under control.",
      "Freeze all investments temporarily to prevent unnecessary risk.",
      "Avoid new loans or credit lines that could worsen the situation.",
      "Track every expense carefully to prevent unnoticed financial leaks.",
      "Focus on cash flow stabilization as the immediate priority.",
      "Reduce commuting or travel costs drastically to save funds.",
      "Prioritize urgent rent and utility payments above all else.",
      "Monitor all bank balances closely to maintain financial awareness.",
      "Temporarily stop non-critical activities that require spending.",
      "Focus on survival-level financial management until stability returns.",
      "Track all small expenses to prevent cash outflow from slipping unnoticed.",
      "Avoid borrowing from friends or multiple sources to prevent complications.",
      "Stop non-essential online purchases immediately.",
      "Pause entertainment spending until finances improve.",
      "Focus strictly on essential food and groceries.",
      "Track daily spending rigorously to maintain control.",
      "Limit discretionary communication expenses temporarily.",
      "Freeze recurring non-essential payments to conserve cash.",
      "Use cash-only for essential purchases to avoid debt.",
      "Track all bills carefully to prevent missed payments.",
      "Avoid non-essential travel to save on costs.",
      "Focus on urgent high-interest debts to reduce financial burden.",
      "Seek halal emergency loans ethically if absolutely necessary.",
      "Prioritize rent and utility payments above all discretionary spending.",
      "Track daily cash inflow and outflow to prevent oversights.",
      "Pause subscription services temporarily to reduce strain.",
      "Avoid credit card usage unless absolutely necessary.",
      "Focus on survival-level financial priorities first.",
      "Track spending categories daily to identify urgent areas for adjustment.",
      "Temporarily halt all non-critical payments to conserve cash.",
      "Review emergency funds frequently to ensure adequacy.",
      "Limit fuel or transport costs to essential trips only.",
      "Focus on essential healthcare spending to maintain wellbeing.",
      "Track urgent debt repayment to avoid penalties or high interest.",
      "Avoid luxury or leisure spending entirely until stability returns.",
      "Track cash balances multiple times daily to maintain full visibility.",
      "Focus entirely on essential living expenses for survival.",
      "Seek professional financial guidance to create an emergency plan.",
      "Track all small payments to avoid unnoticed outflows.",
      "Temporarily stop discretionary activities that consume funds.",
      "Focus on short-term financial stabilization as the immediate goal.",
      "Avoid risky financial commitments that could worsen the situation.",
      "Track and review financial priorities daily to remain disciplined.",
      "Freeze all non-essential spending temporarily to conserve cash.",
      "Prioritize urgent debt repayment ethically and systematically.",
      "Use strict cash budgeting daily to maintain control over funds.",
      "Track all essential income sources to ensure nothing is missed.",
      "Avoid high-risk decisions entirely to prevent further losses."
      
      
    ]
  };
  

  
  